### ISSUE TITLE
two readfile methods

### ISSUE THREAD

**Issue by alanswx** [jsooter/RichFilemanager-Python3Flask#7]
I am not sure why we ended up with two methods for readfile. I assume python just uses the second one?

**Comment by jsooter** [comment]
The second one should over-ride the first one. I'm not sure how two got in there... The first one uses FileManagerResponse so I wonder if the second one is correct... Or perhaps there are supposed to be two methods and I messed up and gave them both the same name. I'll see if I can dig into it today.

**Comment by alanswx** [comment]
The first readfile should be getinfo - they renamed getfile getinfo, and I renamed it readfile incorrectly.
