### ISSUE TITLE
copy is wrong

### ISSUE THREAD

**Issue by alanswx** [jsooter/RichFilemanager-Python3Flask#8]
I think the parameters changed to source and target

**Comment by jsooter** [comment]
Sorry, was way too busy this weekend to review it but I will as soon as a get a spare minute. I'll merge anything you want to modify in the mean time.

**Comment by alanswx** [comment]
I will try to get back to fixing this. I am integrating it into another project - and started to notice some problems. I need to figure out how to go through and test each function.

**Comment by alanswx** [comment]
fixed in pull request #10
